### ISSUE TITLE
Fails to parse Wallet Journal

### ISSUE THREAD

**Issue by minustar** [evemondevteam/evemon#12]
Looking at the trace log file, I see a number of 

```
0d 8h 37m 51s > ExceptionHandler.LogException - Handled exception
    System.InvalidOperationException: There is an error in XML document (103, 189). ---> System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderCCPAPIResult1.Read3_Item(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderCCPAPIResult1.Read4_SerializableAPIWalletJournal(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderCCPAPIResult1.Read5_Item(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderCCPAPIResult1.Read6_eveapi()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at EVEMon.Common.Util.DeserializeAPIResultCore[T](IXPathNavigable doc, XslCompiledTransform transform) in EVEMon.Common\Util.cs:line 386
```

Looking at the XML that EveMon gets, the argument that causes the error is `argID1`, which stores a value much greater than what an `Int32` can store. 

An example of the line that causes the crash:

``` xml
       <row date="2016-07-06 22:54:22" refID="12842811165" refTypeID="1" ownerName1="xxxx" ownerID1="0000" ownerName2="yyyy" ownerID2="0000" argName1="" argID1="1021479764260" amount="0.00" balance="30528002191.92" reason="" taxReceiverID="" taxAmount="" owner1TypeID="1380" owner2TypeID="1377" />
```

Looking over https://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/constants.html#reference-type, it seems that the `argID1` stores the ID of the station where the trade happened; however, where it fails is always a citadel.

**Comment by tavise** [comment]
I just did my first player trade in a citadel yesterday and I am encountering this issue now as well.

**Comment by minustar** [comment]
Like it's been mentioned in another [issues thread](https://github.com/evemondevteam/evemon/issues/3), it seams that an `int` needs to be changed to a `long` to solve that issue.

**Comment by elliena-bulmer** [comment]
I will look at it and see if i can make a quick fix for it. shouldn't be very hard.

**Comment by elliena-bulmer** [comment]
@tavise  & @minustar : I'm trying to reproduce the issue but cannot seems to find where you see the trace. I've added a trace output locally but I still don't get the issue to show up even with some citadel purchases and player trading (and player donation) in citadels. any help? Also I've potentially found where the said issue lays but I'd prefer to see the bug first to make sure the fix does work. Thanks ! :)

**Comment by JimiC** [comment]
@elliena-bulmer 
`trace.txt` resides in `%APPDATA%\EVEMon` directory. You can access it also from "Tools>Option>General>EVEMon Data Directory button".

**Comment by minustar** [comment]
I ran EVEMon thru the VS2015 debugger.

**Comment by elliena-bulmer** [comment]
@minustar , @tavise : Issue should be fixed. If you can grab the changes and let me know if you still have the issue, would appreciate a lot. Also the transactions should appear in the wallet transaction now without skipping the Citadel lines; although the names of the citadels are not resolved yet. Working on it.

**Comment by elementx54** [comment]
I grabbed the changes and my wallet is back after my player trade in the citadel. So for me it is an improvement!  

I did not check the skipping lines for the wallet transaction so someone else will have to weigh in on that.
