### ISSUE TITLE
Can I host my own evemon on my server?

### ISSUE THREAD

**Issue by rmcginnis** [evemondevteam/evemon#15]
under help in evemon I see two lines for bitbucket and GitHub that says 

"for hosting this project" and " for hosting this project and providing our representation site"

**Comment by Rutix** [comment]
You could of course put the source code of EVEMon in your own source control. The question is why would you want this? Those two lines you are referencing are talking about the code and https://evemondevteam.github.io/evemon/ .

**Comment by Ashilta** [comment]
I'll close this, as it isn't strictly an issue. You can always drop us an e-mail if you have questions.
