### ISSUE TITLE
Installer doen't see .NET Framework

### ISSUE THREAD

**Issue by Vampire2008** [evemondevteam/evemon#30]
Hello!
When I try to install EVEMon it said that I don't have .NET Framework and started downloading it.
But I have it.
System: Windows 10 (Anniverthary Build)
Installed .NET Framework: 4.6.2

**Comment by Aftersky** [comment]
Same issue here. I came here to find binary package but it's not available. 

Pretty dumb to make the installer requires specific version of dependencies, at least make it skippable during the install process jesus.

**Comment by JimiC** [comment]
Until this is fixed try this workaround.
1. Open a command console
2. Navigate to the folder where the installer is.
3. Type the installer executable file (i.e EVEMon-install-3.0.2.exe) and add as argument `/SKIPDOTNET`.

This should bypass the .NET version check.
