### ISSUE TITLE
AWU Incorrect Pre-reqs.

### ISSUE THREAD

**Issue by Frost212** [evemondevteam/evemon#35]
Currently using Evemon v 3.0.2 for windows, and it is showing AWU's requirements as Weapon Upgrades 5 still. It was changed to be Weapon Upgrades 4 in a previous patch.

**Comment by elliena-bulmer** [comment]
I'm assuming the next release will have the updated version of the SDE (static data export) and will fix this issue.

The SDE data is build-in with Evemon versions to prevent refetching the whole skill/item/module/etc requirements/info/description/etc from the net every single time you boot the application. Sadly it has the side effect that if the version used by evemon is not in pair with the game data, that kind of issue is likely to happen.

**Comment by Ashilta** [comment]
This issue is resolved by bringing the EVEMon Datafiles in line with the latest EVE SDE.
