### ISSUE TITLE
Crash on Queueing up APIs

### ISSUE THREAD

**Issue by acl1704** [evemondevteam/evemon#39]
Appears to occur when queueing up multiple characters of a mix of both Alpha and Omega. Needs further testing to see if it's widely reproducible.

> 0d 0h 00m 13s > ExceptionHandler.LogException - Handled exception
>     System.InvalidOperationException: There is an error in XML document (16, 188). ---> System.OverflowException: Value was either too large or too small for an Int32.
>    at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
>    at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderCCPAPIResult1.Read3_Item(Boolean isNullable, Boolean checkType)
>    at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderCCPAPIResult1.Read4_SerializableAPIWalletJournal(Boolean isNullable, Boolean checkType)
>    at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderCCPAPIResult1.Read5_Item(Boolean isNullable, Boolean checkType)
>    at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderCCPAPIResult1.Read6_eveapi()
>    --- End of inner exception stack trace ---
>    at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
>    at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
>    at EVEMon.Common.Util.DeserializeAPIResultCore[T](IXPathNavigable doc, XslCompiledTransform transform) in EVEMon.Common\Util.cs:line 386

**Comment by elliena-bulmer** [comment]
Should be fixed with #23 which should be in the next release.
