### ISSUE TITLE
Feature Request: Bring back multiple open plan windows for a single character.

### ISSUE THREAD

**Issue by elementx54** [evemondevteam/evemon#4]
First off, thanks for this awesome tool!

I liked how before you could have as many open plan windows for a single character as you wanted. Now I am limited to a single window per character. Multiple plan windows made designing a complicated long term plan easy as you could see parts of it in small chunks in separate plans, which were not completely finished or in the correct order.

Just something I wish was back.

**Comment by JimiC** [comment]
Please take this to http:evemon.uservoice.com.
