### ISSUE TITLE
Any movement on this project?

### ISSUE THREAD

**Issue by nuadi** [evemondevteam/evemon#56]
Right, so after a review of activity, issues, forums, etc. it seems that this project has either stalled or been abandoned. Am I wrong? Is there activity going on elsewhere - other than GitHub/Bitbucket - that I missed?

I ask because I have features I need, and am preparing to implement them myself. Should I submit a pull request back to you lot or figure out how to host my own version?

Hope all is well on your ends of the keyboards.

**Comment by Ashilta** [comment]
Hello,

The project is still very much alive. There's a tremendous amount to get done before June which will include, but is not limited to, a complete re-write of the authentication routines. This is a huge undertaking, and I'm working with a small group of people that I know well to put this change into effect, and the associated changes to the API queries that EVEMon uses.

If I'm honest, I'd hold fire on submitting PRs for now, as if your functionality makes any API calls, they'll need refactoring after the merge from where I'm doing the authentication refactor.

Ash

**Comment by nuadi** [comment]
Okay, glad this is still active. I'll make a note to avoid API calls then.
