### ISSUE TITLE
Unable to Download EVEMon from Website

### ISSUE THREAD

**Issue by ddouglas493** [evemondevteam/evemon#58]
Had to download it from the EVEO forums. Got my hands on v3.0 from here:
 - https://forums.eveonline.com/default.aspx?g=posts&t=6765

But the big green button on https://evemondevteam.github.io/evemon/# does not work at all.

**Comment by Ashilta** [comment]
Hello,

I'm afraid I'm simply unable to reproduce this - I've been able to download 3.0.3 using the big green button at the link you provided.
