### ISSUE TITLE
Crash on drag&drop in skill browser

### ISSUE THREAD

**Issue by TheFlow0360** [evemondevteam/evemon#68]
I accidentally dragged an entry from the skill browser (it must be a skill, not a group) and the application instantly crashes when  moving the mouse (inside ItemDrag event a null reference occurs). Doesn't happen in any of the other data browser trees, but these seem to be different controls.

    EVEMon Version: 3.0.3.4658
    .NET Runtime Version: 4.0.30319.42000
    Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1
    Executable Path: "C:\Program Files (x86)\EVEMon\EVEMon.exe" 

    System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
       bei EVEMon.SkillPlanner.SkillSelectControl.tvItems_ItemDrag(Object sender, ItemDragEventArgs e) in EVEMon\SkillPlanner\SkillSelectControl.cs:Zeile 1255.
       bei System.Windows.Forms.TreeView.OnItemDrag(ItemDragEventArgs e)
       bei System.Windows.Forms.TreeView.TvnBeginDrag(MouseButtons buttons, NMTREEVIEW* nmtv)
       bei System.Windows.Forms.TreeView.WmNotify(Message& m)
       bei System.Windows.Forms.TreeView.WndProc(Message& m)
       bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

    Datafile report:
      eve-blueprints-en-US.xml.gzip (201KiB - 219eb76e35e9c1df32d2b7f21268582c)
      eve-certificates-en-US.xml.gzip (45KiB - 540000f7c111354769a54fa31e57d411)
      eve-geography-en-US.xml.gzip (531KiB - c9f5f87b8d330a9807d8a29211547791)
      eve-items-en-US.xml.gzip (1980KiB - 4d7be11780cc5865d858cbbf5d3ed2c5)
      eve-masteries-en-US.xml.gzip (21KiB - 3668b50996fc40a0c0853fec427b5712)
      eve-properties-en-US.xml.gzip (57KiB - 1e561036689c116fd39755ed30c20bda)
      eve-reprocessing-en-US.xml.gzip (102KiB - 7ef72dae81f0dd200ef8f31c90fcb762)
      eve-skills-en-US.xml.gzip (23KiB - 5c6f3a9ea32a6f135b12f82ac6d8d2ce)

    Diagnostic Log:
    0d 0h 00m 00s > Starting up
    0d 0h 00m 00s > EveMonClient.Initialize - begin
    0d 0h 00m 00s > Program.StartupAsync - done
    0d 0h 00m 00s > Settings.TryDeserializeFromFile - begin
    0d 0h 00m 00s > Settings.TryDeserializeFromFile - done
    0d 0h 00m 00s > Settings.Import - begin
    0d 0h 00m 00s > EveMonClient.OnSchedulerChanged
    0d 0h 00m 00s > Settings.Import - done
    0d 0h 00m 00s > EveMonClient.OnSettingsChanged
    0d 0h 00m 00s > Main loop - start
    0d 0h 00m 00s > MainWindow.OnLoad
    0d 0h 00m 00s > TimeCheck.ScheduleCheck - in 00:00:01
    0d 0h 00m 00s > UpdateManager.ScheduleCheck - in 00:00:10
    0d 0h 00m 00s > Main window - loaded
    0d 0h 00m 00s > EveIDToName.Import - begin
    0d 0h 00m 00s > EveIDToName.Import - done
    0d 0h 00m 00s > Datafiles.Load - begin
    0d 0h 00m 01s > TimeCheck.BeginCheckAsync
    0d 0h 00m 01s > EveMonClient.OnServerStatusUpdated
    0d 0h 00m 02s > TimeCheck.CheckFailure - Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte 128.138.141.172:13
    0d 0h 00m 02s > TimeCheck.ScheduleCheck - in 00:01:00
    0d 0h 00m 03s > Datafiles.Load - done
    0d 0h 00m 03s > Settings.ImportData - begin
    0d 0h 00m 03s > EveMonClient.OnCharacterImplantSetCollectionChanged - John Crendravus
    0d 0h 00m 03s > EveMonClient.OnCharacterSkillQueueUpdated - John Crendravus
    0d 0h 00m 03s > EveMonClient.OnCharacterUpdated - John Crendravus
    0d 0h 00m 03s > EveMonClient.OnCharacterCollectionChanged
    0d 0h 00m 03s > EveMonClient.OnAPIKeyCollectionChanged
    0d 0h 00m 03s > EveMonClient.OnCharacterPlanCollectionChanged - John Crendravus
    0d 0h 00m 03s > EveMonClient.OnMonitoredCharactersChanged
    0d 0h 00m 04s > Settings.ImportData - done
    0d 0h 00m 04s > EveMonClient.OnSettingsChanged
    0d 0h 00m 05s > EveMonClient.OnCharacterUpdated - John Crendravus
    0d 0h 00m 05s > EveMonClient.OnCharacterListUpdated - 6338677 (John Crendravus)
    0d 0h 00m 05s > EveMonClient.OnAPIKeyInfoUpdated - 6338677 (John Crendravus)
    0d 0h 00m 07s > EveMonClient.OnCharacterStandingsUpdated - John Crendravus
    0d 0h 00m 07s > EveMonClient.OnCharacterEVEMailMessagesUpdated - John Crendravus
    0d 0h 00m 07s > EveMonClient.OnNotificationSent - An error occured while querying the personal kill log.
    0d 0h 00m 07s > EveMonClient.OnCharacterEVEMailingListsUpdated - John Crendravus
    0d 0h 00m 07s > EveMonClient.OnCharacterWalletJournalUpdated - John Crendravus
    0d 0h 00m 07s > EveMonClient.OnRefTypesUpdated
    0d 0h 00m 08s > EveMonClient.OnAccountStatusUpdated - 6338677 (John Crendravus)

**Comment by TheFlow0360** [comment]
Ok, cannot reproduce in master so I guess this was already fixed?

**Comment by aydjay** [comment]
This may have been resolved with #54

**Comment by TheFlow0360** [comment]
@aydjay yes that sounds similar
